In [1]:
import pandas as pd
import numpy as np
import random

from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.metrics import confusion_matrix, f1_score

from imblearn.over_sampling import SMOTE

In [2]:
X  = pd.read_csv("tornado-xtrain.csv")
xCols = X.columns
X = pd.DataFrame(preprocessing.scale(X))
X.columns = xCols
y = pd.read_csv("tornado-ytrain.csv", header=None, index_col=0)

# from feature importances as determined by decision tree
"""unimportantFeatures = ["EVENT_ID", "median_income", "population_density", "weekend", "average_range", "average_latitude", "average_longitude", "percent_land", "multi_vortex"]
X = X.drop(columns=unimportantFeatures)"""
X

/home/zaned/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  This is separate from the ipykernel package so we can avoid doing imports until


EVENT_ID  median_income  population_density  housing_units_density  \
0     -0.659569       1.098649            0.012169              -0.005170   
1      0.790458       0.428080            3.270950               3.242428   
2     -1.431252       0.487838           -0.201964              -0.214536   
3      0.470828       3.065708            0.095714               0.109644   
4     -1.333534       0.721748           -0.196180              -0.210999   
5      0.933694       3.497331            0.972811               0.911413   
6     -0.943042      -0.978364           -0.176258              -0.185270   
7     -1.501964      -1.024805           -0.186284              -0.201029   
8     -1.422917       0.667027           -0.175358              -0.188808   
9      0.346118      -0.941912           -0.186412              -0.187200   
10    -0.273424      -1.198017           -0.191039              -0.201029   
11     1.612024       0.396153            1.634619               1.915152   
12     0.324286      -0.553059            0.116279               0.162388   
13     0.037847      -0.346467            0.354833               0.503293   
14    -0.817046      -0.038543           -0.217131              -0.233190   
15     0.487781      -0.121095           -0.221887              -0.238335   
16     1.432740      -0.005506           -0.218159              -0.232547   
17     0.233057      -0.254013           -0.218802              -0.234155   
18    -0.783253       0.101802           -0.190268              -0.201994   
19     1.320046      -0.273733           -0.156464              -0.166939   
20    -0.510969      -0.902472           -0.044642              -0.035722   
21     0.301499       1.097966            0.956102               1.182850   
22     0.506679       0.828629           -0.196052              -0.209069   
23    -0.246318       0.433032           -0.104538              -0.119662   
24    -1.404876      -0.549644           -0.218031              -0.233833   
25    -0.558140      -0.843824           -0.148752              -0.147642   
26     1.288999      -1.108807           -0.201065              -0.206818   
27    -0.248230      -0.933034           -0.108265              -0.117411   
28     1.605342       0.004997           -0.003802              -0.003769   
29     1.597878      -0.265538           -0.220087              -0.236084   
...         ...            ...                 ...                    ...   
11676  0.477925      -1.061855           -0.162634              -0.168225   
11677  1.656256       0.126218           -0.201964              -0.215501   
11678 -1.431247       0.587122           -0.175487              -0.186235   
11679 -0.736610       0.026507           -0.217774              -0.233833   
11680  1.685147      -0.136546           -0.193224              -0.203280   
11681  1.393565      -0.223537            0.231443               0.202589   
11682 -0.724611       0.967182           -0.029218              -0.036044   
11683 -1.482322       2.498350            2.076638               1.947313   
11684  1.303414       0.004997           -0.003802              -0.003769   
11685 -1.486810      -1.001585           -0.104152              -0.106798   
11686  0.838651      -0.177267           -0.175487              -0.185270   
11687  1.582620       0.700747            0.259977               0.284921   
11688 -1.534508      -1.222347           -0.170474              -0.183341   
11689 -0.408556      -1.733533           -0.213661              -0.231903   
11690 -0.220814      -0.562876           -0.153894              -0.160185   
11691  0.457233      -1.048879           -0.104923              -0.110657   
11692 -1.549992       0.582597           -0.088857              -0.100044   
11693  0.720306       0.700747            0.259977               0.284921   
11694  1.400186       1.764694           -0.130629              -0.148928   
11695  0.789426      -0.177267           -0.175487              -0.185270   
116

## KNN

In [3]:
knn = KNeighborsClassifier()

## RNN

In [4]:
rnn = RadiusNeighborsClassifier(outlier_label=0)

## Cross Validation Functions

In [5]:
def testClassifier(clf, X, y):
    y_pred = clf.predict(X)
    cm = confusion_matrix(y, y_pred)
    #cm_normalized = [cm[i]/sum(cm[i]) for i in range(len(cm))]
    f1 = f1_score(y, y_pred, average = 'macro')
    
    return cm, f1

In [6]:
def crossValidate(clf):
    kf = KFold(n_splits=10)
    cms = []
    f1s = []
    for train_fold, test_fold in kf.split(X):
        
        sm = SMOTE(sampling_strategy='not majority')
        X_train_balanced, y_train_balanced = sm.fit_resample(X.iloc[train_fold], y.iloc[train_fold].values.ravel())
    
        clf.fit(X_train_balanced, y_train_balanced.ravel())
        cm, f1 = testClassifier(clf, X.iloc[test_fold], y.iloc[test_fold])
        cms.append(cm)
        f1s.append(f1)
    
    return sum(cms), np.mean(f1)

## Testing Defaults

In [7]:
for c in [knn, rnn]:
    print(crossValidate(c))
    print()

(array([[8946, 1728,  131],
       [ 297,  395,  102],
       [   5,   59,   43]]), 0.40666778448468593)

(array([[10134,   647,    24],
       [  675,    96,    23],
       [   79,    14,    14]]), 0.3597932273185263)



## KNN Hyperparameter Optimization

* n_neighbors
* metric
* columns? TODO

In [8]:
krange = range(1, 15)

In [9]:
for k in krange:
    print(k)
    for m in ["euclidean", "manhattan"]:
        knn = KNeighborsClassifier(n_neighbors=k, metric=m)
        print(crossValidate(knn))

1
(array([[9796,  937,   72],
       [ 456,  266,   72],
       [  15,   54,   38]]), 0.41012548675502475)
(array([[10031,   717,    57],
       [  489,   236,    69],
       [   17,    52,    38]]), 0.4048092508210495)
2
(array([[9948,  791,   66],
       [ 481,  239,   74],
       [  15,   52,   40]]), 0.4130707459928044)
(array([[10133,   618,    54],
       [  505,   221,    68],
       [   19,    47,    41]]), 0.4490426304811455)
3
(array([[9286, 1417,  102],
       [ 355,  342,   97],
       [  10,   57,   40]]), 0.38308286818376985)
(array([[9532, 1197,   76],
       [ 396,  307,   91],
       [   9,   55,   43]]), 0.42858844022685827)
4
(array([[9423, 1278,  104],
       [ 371,  323,  100],
       [  11,   52,   44]]), 0.4047721065079728)
(array([[9657, 1072,   76],
       [ 405,  294,   95],
       [  10,   53,   44]]), 0.43582818440910637)
5
(array([[8964, 1712,  129],
       [ 302,  385,  107],
       [   5,   57,   45]]), 0.41121929453797756)
(array([[9215, 1492,   98],
   

## RNN Hyperparameter Optimization

* radius
* metric
* columns? TODO

In [10]:
rrange = np.arange(1.0, 10.0, 0.5)

In [11]:
for r in rrange:
    print(r)
    for m in ["euclidean", "manhattan"]:
        rnn = RadiusNeighborsClassifier(outlier_label=0, radius=r, metric=m)
        print(crossValidate(rnn))

1.0
(array([[10129,   653,    23],
       [  670,   101,    23],
       [   79,    14,    14]]), 0.35901607707495214)


/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packag

(array([[10755,    50,     0],
       [  788,     6,     0],
       [  106,     1,     0]]), 0.32061520260278026)
1.5
(array([[9205, 1499,  101],
       [ 482,  238,   74],
       [  57,   24,   26]]), 0.3607337150018514)


/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zaned/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([[10677,   126,     2],
       [  777,    14,     3],
       [  101,     3,     3]]), 0.3266933735775395)
2.0
(array([[8886, 1720,  199],
       [ 355,  276,  163],
       [  29,   37,   41]]), 0.38498504735441497)
(array([[10519,   278,     8],
       [  736,    47,    11],
       [   92,     9,     6]]), 0.3518308762235578)
2.5
(array([[8963, 1540,  302],
       [ 293,  275,  226],
       [  18,   31,   58]]), 0.38130585582007726)
(array([[10264,   525,    16],
       [  685,    87,    22],
       [   81,    16,    10]]), 0.3568513563488438)
3.0
(array([[9196, 1190,  419],
       [ 289,  246,  259],
       [  14,   18,   75]]), 0.41551496036557767)
(array([[9951,  812,   42],
       [ 615,  142,   37],
       [  69,   20,   18]]), 0.3507496877608531)
3.5
(array([[9408,  946,  451],
       [ 284,  221,  289],
       [  11,   17,   79]]), 0.41921912953650614)
(array([[9600, 1137,   68],
       [ 540,  193,   61],
       [  54,   30,   23]]), 0.3439005927633954)
4.0
(array([[9501

## Best Model: RNN with radius=6.5